version: "3"
services: 
  sql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Qwerty!@#"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"